---
- name: "Update and upgrade apt packages"
  become: true
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400
- name: "Install packages"
  become: true
  apt:
    pkg:
      - exa
      - git
      - vim
      - zsh
      - tree
      - htop
      - curl
      - wget
