---
- include_tasks: apt.yml
- include_tasks: zsh.yml
- include_tasks: ssh_config.yml

- name: 'iptables config legacy'
  become: true
  command: "{{ item }}"
  with_items:
  - /usr/sbin/iptables -F
  - update-alternatives --set iptables /usr/sbin/iptables-legacy
  - update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy

# - name: 'reboot after ip tables'
#   reboot:
