---
- name: "Update and upgrade apt packages"
  become: yes
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400
- name: "Install packages"
  become: yes
  apt:
    pkg:
      - git
      - zsh
- name: "clone oh-my-zsh for users"
  command: "git clone -c core.autocrlf=input --depth=1 https://github.com/robbyrussell/oh-my-zsh.git .oh-my-zsh"
  args:
    chdir: "~{{ ansible_user_id }}"
    creates: "~{{ ansible_user_id }}/.oh-my-zsh"

- name: "set permissions of oh-my-zsh for users"
  file:
    path: "~{{ ansible_user_id }}/.oh-my-zsh"
    # Prevent the cloned repository from having insecure permissions. Failing to do
    # so causes compinit() calls to fail with "command not found: compdef" errors
    # for users with insecure umasks (e.g., "002", allowing group writability).
    mode: "go-w"
    recurse: yes

- name: "set default shell for users"
  become: yes
  user:
    name: pi
    shell: /bin/zsh

- name: "download zsh-syntax-highlighting"
  git:
    repo: "https://github.com/zsh-users/zsh-syntax-highlighting.git"
    dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting

- name: "download zsh-autosuggestions"
  git:
    repo: "https://github.com/zsh-users/zsh-autosuggestions"
    dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions

- name: "write .zshrc for users"
  template:
    src: zshrc.sh.j2
    dest: "~{{ ansible_user_id }}/.zshrc"
    backup: yes
    mode: "u=rw,go=r"
